name: JHU Update

on:
  schedule:
    - cron: '30 7 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        env:
          EMAIL_SENDER: ${{secrets.EMAIL_SENDER}}
          EMAIL_RECIPIENT: ${{secrets.EMAIL_RECIPIENT}}
          MAILGUN_API_KEY: ${{secrets.MAILGUN_API_KEY}}
        run: python JHU_Update.py
      - name: Commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git add .
          git commit -m 'Update CSV file'
          git push origin main
